config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope(:path_names => { :new => "nueva", :edit => "editar" }) do
    resources :entries, :path => 'quejas'
  end
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#login'

  
  root :to => 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  after_create :set_identificator

  EMAIL = 'comite.etica@cimav.edu.mx'

  def set_identificator
    con = Entry.maximum(:consecutive)
    if con.nil?
      con = 1
    else
      con += 1
    end
    consecutive = "%03d" % con
    self.consecutive = con
    self.year = self.created_at.year
    self.identificator = "B-#{self.year}-#{consecutive}"
    self.save(:validate => false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  skip_before_action :verify_authenticity_token

  def auth_required
    redirect_to '/login' unless authenticated?
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  
  before_action :auth_required
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
  	if current_user.is_admin?
      @entries = Entry.order(created_at: :DESC)
    else
      @entries = current_user.entries
    end
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user_id  = current_user.id

    if @entry.save
      BuzonMailer.send_buzon(@entry).deliver_now          
      redirect_to '/'
    else 
       puts @entry.errors.full_messages
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:message)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login 
    render layout: false
  end 

  def create
    
    session[:user_email] = auth_hash['info']['email']
    session[:user_name] = auth_hash['info']['name']

    if authenticated?
      if !session[:requested_url].blank?
        redirect_to session[:requested_url]
      else
        redirect_to '/'
      end
    else
      @title = "Error 401" 
      @message = "El usuario no está autorizado para utilizar esta aplicación."
      render layout: 'standalone', template: 'application/error', :status => 401
    end
  end

  def destroy
    reset_session
    redirect_to '/login'
  end

  def failure
    @title = "Error 403" 
    @message = "El método de autenticación falló."
    render layout: 'standalone', template: 'application/error', :status => 403
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticated?
    if session[:user_email].blank? 
      session[:requested_url] = request.original_url
      return false
    end
    if session[:user_auth].blank?

      user = User.where(email: session[:user_email]).first

      if !user 
      	user = User.new
      	user.email = session[:user_email]
      	user.name = session[:user_name]
      	user.save
      	session[:user_auth] = user
      	session[:user_id] = user.id
      else
        session[:user_auth] = user && user.email == session[:user_email]
        if session[:user_auth]
          session[:user_id] = user.id
        end
      end
    else
      session[:user_auth]
    end
  end

  def is_admin?
    return current_user.admin
  end 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="level">
  <div class="level-left">
    <% if current_user.is_admin %>
      <h1>Quejas</h1>
    <% else %>
      <h1>Mis quejas</h1>
    <% end %>
  </div>
  <div class="level-right">
  	<a href="<%= new_entry_url %>" class="button is-link">Nueva queja</a>
  </div>
</div>
<% if @entries.count == 0 %>
  <div class="empty">
    No tienes quejas, <a href="<%= new_entry_url %>">¿Deseas agregar una nueva?</a>
  </div>
<% end %>
<% @entries.each do |entry| %>
  <div class="entry">
    <h2><%= entry.identificator %></h2>
    <span class="extra"><%= entry.user.name %> - <%= l entry.created_at.to_datetime, format: "%Y-%m-%d %H:%M" rescue '--' %></span>
    <p><%= entry.message %></p>
  </div>
<% end %>

app/views/entries/new.html.erb
<h1>Mi nueva queja</h1>
<%= form_with model: @entry do |f| %>
  <%= f.text_area :message, class: 'input' %>
  <%= f.submit "Enviar", class: 'button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='has-navbar-fixed-top'>
  <head>
    <title>Buzón CIMAV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/"><strong>Buzón CIMAV / <%= current_user.name %></strong></a>
      </div>
      <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-success" href="/logout">
            <strong>Salir</strong>
          </a>
        </div>
      </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>

app/views/layouts/standalone.html.erb
<!DOCTYPE html>
<html class='has-navbar-fixed-top'>
  <head>
    <title>Asistencia CIMAV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>